config/urls.py
from django.conf.urls.static                            import static
from django.contrib                                     import admin
from django.conf                                        import settings
from django.urls                                        import path, include


urlpatterns = [

    path('',                                include('zigida.apps.urls')),

]

if settings.DEBUG and settings.IS_ENV == 'DEV':

    import debug_toolbar

    urlpatterns = [

        # path('admin/',                              admin.site.urls),
        path('__debug__/',                          include(debug_toolbar.urls)),

    ] + urlpatterns

    urlpatterns = urlpatterns + static(
                            settings.STATIC_URL, document_root=settings.STATIC_ROOT
                        )
    urlpatterns = urlpatterns + static(
                            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
                        )

zigida/apps/urls.py
from django.urls                                import path, include


urlpatterns = [

        # path('api/',                        include('zigida.apps.api.urls')),
        # path('autocomplete/',               include('zigida.apps.autocomplete.urls')),
        path('',                                include('zigida.apps.web.urls')),

    ]

zigida/apps/web/stores/urls.py
from django.urls                                        import path

from zigida.apps.web.products.products.list.views       import ProductMenListView
from zigida.apps.web.products.products.list.views       import ProductWomenListView


app_name = 'stores'

urlpatterns = [

    path('mens/',               ProductMenListView.as_view(),               name='mens'),
    path('womens/',             ProductWomenListView.as_view(),             name='womens'),

]

zigida/apps/web/urls.py
from django.urls                                                import path, include

from zigida.apps.web.home.views                                 import HomeView
from zigida.apps.web.home.views                                 import AboutView, Zig404View
from zigida.apps.web.sr_users.views                             import UserLoginView, \
                                                                        UserRegisterView, UserLogoutView
# from zigida.apps.web.products.list.views                        import ZigMensView
# from zigida.apps.web.products.list.views                        import ZigWomensView

# from zigida.apps.web.accounting.addresses.urls                  import urlpatterns as addresses_urls
# from zigida.apps.web.accounting.banks.urls                      import urlpatterns as banks_urls
# from zigida.apps.web.accounting.coupons.urls                    import urlpatterns as coupons_urls
# from zigida.apps.web.accounting.items.urls                      import urlpatterns as items_urls
# from zigida.apps.web.accounting.orders.urls                     import urlpatterns as orders_urls
# from zigida.apps.web.accounting.payments.urls                   import urlpatterns as payments_urls
# from zigida.apps.web.accounting.receipts.urls                   import urlpatterns as receipts_urls
# from zigida.apps.web.accounting.refunds.urls                    import urlpatterns as refunds_urls
# from zigida.apps.web.accounting.vouchers.urls                   import urlpatterns as vouchers_urls

# from zigida.apps.web.categories.urls                            import urlpatterns as categories_urls
# from zigida.apps.web.customers.urls                             import urlpatterns as customers_urls
# from zigida.apps.web.dashboard.urls                             import urlpatterns as dashboard_urls
# from zigida.apps.web.openinghours.urls                          import urlpatterns as openinghours_urls
from zigida.apps.web.products.urls                              import urlpatterns as products_urls
# from zigida.apps.web.sr_issues.urls                             import urlpatterns as sr_issues_urls
# from zigida.apps.web.sr_users.urls                              import urlpatterns as sr_users_urls
# from zigida.apps.web.stores.urls                                import urlpatterns as stores_urls


app_name = 'web'

urlpatterns = [

        path('',                            HomeView.as_view(),                     name='home'),
        path('about/',                      AboutView.as_view(),                    name='about'),
        # path('contact/',                  ZigContactView.as_view(),               name='contact'),
        # path('mens/',                     ZigMensView.as_view(),                  name='mens'),
        # path('womens/',                   ZigWomensView.as_view(),                name='womens'),
        path('404/',                        Zig404View.as_view(),                   name='404'),

        path('login/',                      UserLoginView.as_view(),                name='login'),
        path('logout/',                     UserLogoutView.as_view(),               name='logout'),
        path('register/',                   UserRegisterView.as_view(),             name='register'),

        # path('customers/',                include('zigida.apps.web.customers.urls')),
        path('issues/',                     include('zigida.apps.web.sr_issues.urls')),
        # path('orders/',                   include('zigida.apps.web.orders.urls')),
        # path('products/',                   include('zigida.apps.web.products.urls')),

    ] + products_urls

zigida/apps/db/accounting/banks/models.py
import uuid

from django.db                                                  import models

from zigida.core.model_mixins                                   import AuditFields, AddressFields
from zigida.core.utils                                          import bank_randcode_gen


# Create your models here.
class Bank(AuditFields, AddressFields):

    uuid_code           = models.UUIDField('ID',  primary_key=True, default=uuid.uuid4, editable=False,                 null=False)

    token_key           = models.UUIDField('TOKEN',     default=uuid.uuid4,             editable=False, blank=True,     null=True)
    code                = models.CharField('CODE',                  max_length=100,     blank=False, default=bank_randcode_gen)

    name                = models.CharField('NAME',                  max_length=100,     blank=True,                     null=True)
    swift_code          = models.CharField('SWIFT CODE',            max_length=100,     blank=True,                     null=True)

    bool_active         = models.BooleanField('IS ACTIVE',          default=True,       blank=True,                     null=True)

    class Meta:
        app_label   = 'banks'
        db_table    = 'banks'
        verbose_name_plural = 'banks'

zigida/apps/db/accounting/coupons/models.py
import uuid
from decimal                                                    import Decimal

from django.core.validators                                     import MinValueValidator
from django.db                                                  import models

from zigida.core.model_mixins                                   import AuditFields
from zigida.core.utils                                          import coup_randcode_gen


# Create your models here.
class Coupon(AuditFields):

    uuid_code           = models.UUIDField('ID',  primary_key=True, default=uuid.uuid4, editable=False,                 null=False)

    token_key           = models.UUIDField('TOKEN',     default=uuid.uuid4,             editable=False, blank=True,     null=True)
    code                = models.CharField('CODE',                  max_length=100,     blank=False, default=coup_randcode_gen)

    title               = models.CharField('TITLE',                 max_length=100,     blank=True,                     null=True)
    amount              = models.DecimalField('AMOUNT',             decimal_places=5,   max_digits=15,
                                                        validators=[MinValueValidator(Decimal(0.00))], default=0.00,    null=True)
    percent             = models.PositiveSmallIntegerField('PERCENT',default=0,         blank=True,                     null=True)
    date_from           = models.DateField('DATE FROM',                                 blank=True,                     null=True)
    date_to             = models.DateField('DATE TO',                                   blank=True,                     null=True)

    bool_active         = models.BooleanField('IS ACTIVE',          default=True,       blank=True,                     null=True)

    class Meta:
        app_label   = 'coupons'
        db_table    = 'coupons'
        verbose_name_plural = 'coupons'

zigida/apps/db/accounting/items/models.py
import uuid

from django.conf                                                import settings
from django.core.validators                                     import MinValueValidator, MaxValueValidator
from django.db                                                  import models

from zigida.core.model_mixins                                   import AuditFields
from zigida.core.utils                                          import item_randcode_gen


# Create your models here.
class Item(AuditFields):

    uuid_code           = models.UUIDField('ID',  primary_key=True, default=uuid.uuid4, editable=False,                 null=False)

    customer            = models.ForeignKey(settings.AUTH_USER_MODEL,       on_delete=models.PROTECT, related_name='items')
    # refund              = models.ForeignKey('refunds.Refund',       on_delete=models.PROTECT, related_name='items',     null=True)
    product             = models.ForeignKey('products.Product',     on_delete=models.PROTECT, related_name='items',     null=True)
    location            = models.ForeignKey('locations.Location',   on_delete=models.PROTECT, related_name='items',     null=True)

    token_key           = models.UUIDField('TOKEN',     default=uuid.uuid4,             editable=False, blank=True,     null=True)
    code                = models.CharField('CODE',                  max_length=100,     blank=False,    default=item_randcode_gen)

    quantity            = models.PositiveSmallIntegerField('QUANTITY',
                                validators=[MinValueValidator(1), MaxValueValidator(999)], default=1,   blank=True,     null=True)

    price_buy           = models.DecimalField('PRICE BUY',              max_digits=19, default=0, decimal_places=2, blank=True)
    price_buy_original  = models.DecimalField('PRICE BUY ORIGINAL',     max_digits=19, default=0, decimal_places=2, blank=True)
    price_sell          = models.DecimalField('PRICE SELL',             max_digits=19, default=0, decimal_places=2, blank=True)
    price_sell_original = models.DecimalField('PRICE SELL ORIGINAL',    max_digits=19, default=0, decimal_places=2, blank=True)

    bool_active         = models.BooleanField('IS ACTIVE', default=True)

    class Meta:
        app_label   = 'items'
        db_table    = 'items'
        verbose_name_plural = 'items'

zigida/apps/db/accounting/orders/models.py
import uuid

from django.conf                                                import settings
from django.db                                                  import models

from zigida.common.global_choices                               import PAYMENT_TYPE, ORDER_TYPE
from zigida.core.model_mixins                                   import AuditFields, OrdersDetailFields
from zigida.core.utils                                          import ord_randcode_gen


# Create your models here.
class Order(AuditFields, OrdersDetailFields):

    uuid_code           = models.UUIDField('ID',  primary_key=True, default=uuid.uuid4, editable=False,                 null=False)

    customer            = models.ForeignKey(settings.AUTH_USER_MODEL,       on_delete=models.PROTECT, related_name='orders')
    billing_address     = models.ForeignKey('addresses.Address', on_delete=models.SET_NULL,  related_name='billing_address',  null=True)
    shipping_address    = models.ForeignKey('addresses.Address', on_delete=models.SET_NULL,  related_name='shipping_address', null=True)
    coupon              = models.ForeignKey('coupons.Coupon',       on_delete=models.PROTECT,   related_name='orders',  null=True)
    location            = models.ForeignKey('locations.Location',   on_delete=models.PROTECT,   related_name='orders',  null=True)
    item                = models.ForeignKey('items.Item',           on_delete=models.PROTECT,   related_name='orders',  null=True)
    payment             = models.ForeignKey('payments.Payment',     on_delete=models.PROTECT,   related_name='orders',  null=True)

    token_key           = models.UUIDField('TOKEN',     default=uuid.uuid4,             editable=False, blank=True,     null=True)
    code                = models.CharField('CODE',                  max_length=100,     blank=False, default=ord_randcode_gen)

    amount              = models.DecimalField('AMOUNT',             decimal_places=5,       max_digits=15, default=0.00,null=True)
    order_type          = models.CharField('ORDER TYPE',            choices=ORDER_TYPE,     max_length=2,               null=True)
    payment_type        = models.CharField('PAYMENT TYPE',          choices=PAYMENT_TYPE,   max_length=2,               null=True)

    class Meta:
        app_label   = 'orders'
        db_table    = 'orders'
        verbose_name_plural = 'orders'

zigida/apps/db/accounting/payments/models.py
import uuid
from decimal                                                    import Decimal

from django.conf                                                import settings
from django.core.validators                                     import MinValueValidator
from django.db                                                  import models

from zigida.common.global_choices                               import PAYMENT_TYPE, CARD_TYPE, MOBILE_MONEY_TYPE
from zigida.core.model_mixins                                   import AuditFields
from zigida.core.utils                                          import pay_randcode_gen


# Create your models here.
class Payment(AuditFields):

    uuid_code           = models.UUIDField('ID',  primary_key=True, default=uuid.uuid4, editable=False,                 null=False)

    customer            = models.ForeignKey(settings.AUTH_USER_MODEL,       on_delete=models.PROTECT, related_name='payments')
    bank                = models.ForeignKey('banks.Bank',           on_delete=models.PROTECT, related_name='payments',  null=True)
    location            = models.ForeignKey('locations.Location',   on_delete=models.PROTECT, related_name='payments',  null=True)

    token_key           = models.UUIDField('TOKEN',     default=uuid.uuid4,             editable=False, blank=True,     null=True)
    code                = models.CharField('CODE',                  max_length=100,     blank=False, default=pay_randcode_gen)

    mpesa_charge_id     = models.CharField('MPESA PAY ID',          max_length=100,                     blank=True,     null=True)
    paypal_charge_id    = models.CharField('PAYPAL PAY ID',         max_length=100,                     blank=True,     null=True)
    stripe_charge_id    = models.CharField('STRIPE PAY ID',         max_length=100,                     blank=True,     null=True)

    amount_paid         = models.DecimalField('AMOUNT PAID',        decimal_places=5,       max_digits=15,
                                            validators=[MinValueValidator(Decimal(0.00))],  default=0.00,               null=True)
    amount_outstanding  = models.DecimalField('OUTSTANDING AMOUNT', decimal_places=5,       max_digits=15,
                                            validators=[MinValueValidator(Decimal(0.00))],  default=0.00,               null=True)
    payment_type        = models.CharField('PAYMENT TYPE',          max_length=1, choices=PAYMENT_TYPE,      blank=True,null=True)
    card_type           = models.CharField('CARD TYPE',             max_length=1, choices=CARD_TYPE,         blank=True,null=True)
    mob_money_type      = models.CharField('MOBILE MONEY TYPE',     max_length=1, choices=MOBILE_MONEY_TYPE, blank=True,null=True)

    class Meta:
        app_label   = 'payments'
        db_table    = 'payments'
        verbose_name_plural = 'payments'

zigida/apps/db/customers/models.py
from django.db import models

# Create your models here.

zigida/apps/db/products/colors/models.py
import uuid

from django.db                                                  import models

from zigida.core.model_mixins                                   import AuditFields
from zigida.core.utils                                          import color_randcode_gen


# Create your models here.
class Color(AuditFields):

    uuid_code           = models.UUIDField('ID',  primary_key=True, default=uuid.uuid4, editable=False,                 null=False)

    token_key           = models.UUIDField('TOKEN',     default=uuid.uuid4,             editable=False, blank=True,     null=True)
    code                = models.CharField('CODE',                  max_length=100,     blank=False, default=color_randcode_gen)

    title               = models.CharField('TITLE',                 max_length=250,     blank=True,                     null=True)
    shade               = models.CharField('SHADE',                 max_length=250,     blank=True,                     null=True)
    Description         = models.TextField('DESCRIPTION',                               blank=True,                     null=True)

    class Meta:
        app_label   = 'colors'
        db_table    = 'colors'
        verbose_name_plural = 'colors'

zigida/templates/includes/arrivals.html
{% load static %}


<!-- /new_arrivals -->
<div class="new_arrivals_agile_w3ls_info">
    <div class="container">
        <h3 class="wthree_text_info">Nouvellement <span>ARRIVÉES</span></h3>
            <div id="horizontalTab">
                <ul class="resp-tabs-list">
                    <li> Pour Hommes</li>
                    <li> Pour Femmes</li>
                    <li> Sacs</li>
                    <li> Chaussures</li>
                </ul>
                <div class="resp-tabs-container">

                <!--/tab_one-->
                {% include 'includes/tab_one.html' %}
                <!--//tab_one-->

                <!--/tab_two-->
                {% include 'includes/tab_two.html' %}
                <!--//tab_two-->

                <!--/tab_tree-->
                {% include 'includes/tab_three.html' %}
                <!--//tab_tree-->

                {% include 'includes/tab_four.html' %}

                </div>
            </div>
        </div>
    </div>
<!-- //new_arrivals -->

zigida/templates/includes/bannerTrending.html
{% load static %}


<!-- banner-bootom-w3-agileits -->
<div class="banner-bootom-w3-agileits">
    <div class="container">
        <h3 class="wthree_text_info">What's <span>Trending</span></h3>
        <div class="col-md-5 bb-grids bb-left-agileits-w3layouts">
            <a href="{% url 'web:womens' %}">
                <div class="bb-left-agileits-w3layouts-inner grid">
                    <figure class="effect-roxy">
                        <img src="{% static 'images/bb1.jpg' %}" alt=" " class="img-responsive" />
                        <figcaption>
                            <h3><span>En</span>Vente </h3>
                            <p>Upto 55%</p>
                        </figcaption>
                    </figure>
                </div>
            </a>
        </div>

        <div class="col-md-7 bb-grids bb-middle-agileits-w3layouts">
            <a href="{% url 'web:mens' %}">
                <div class="bb-middle-agileits-w3layouts grid">
                    <figure class="effect-roxy">
                        <img src="{% static 'images/bottom3.jpg' %}" alt=" " class="img-responsive" />
                        <figcaption>
                            <h3><span>En</span>Vente </h3>
                            <p>Upto 55%</p>
                        </figcaption>
                    </figure>
                </div>
            </a>
            <a href="{% url 'web:mens' %}">
                <div class="bb-middle-agileits-w3layouts forth grid">
                    <figure class="effect-roxy">
                        <img src="{% static 'images/bottom4.jpg' %}" alt=" " class="img-responsive">
                        <figcaption>
                            <h3><span>En</span>Vente </h3>
                            <p>Upto 65%</p>
                        </figcaption>
                    </figure>
                </div>
            </a>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<!--/grids-->
    <div class="agile_last_double_sectionw3ls">
        <div class="col-md-6 multi-gd-img multi-gd-text ">
            <a href="{% url 'web:womens' %}"><img src="{% static 'images/bot_1.jpg' %}" alt=" ">
                <h4>Flat <span>50%</span> offer</h4>
            </a>
        </div>
        <div class="col-md-6 multi-gd-img multi-gd-text ">
            <a href="{% url 'web:womens' %}"><img src="{% static 'images/bot_2.jpg' %}" alt=" ">
                <h4>Flat <span>50%</span> offer</h4>
            </a>
        </div>
        <div class="clearfix"></div>
    </div>
<!--/grids-->

zigida/templates/includes/menubar.html
{% load static %}


<div class="ban-top">
    <div class="container">
        <div class="top_nav_left">
            <nav class="navbar navbar-default">
                <div class="container-fluid">

                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav menu__list">
                            <li class="{% if page_name == 'home' %}active menu__item--current {% endif %}menu__item">
                                <a class="menu__link" href="/">Accueil <span class="sr-only">{% if page_name == 'home' %}(current){% endif %}</span></a>
                            </li>
                            <li class="{% if page_name == 'about' %}active menu__item--current {% endif %} menu__item"><a class="menu__link" href="{% url 'web:about' %}">À propos</a></li>
                            <li class="dropdown menu__item">

                                <a href="{% url 'web:mens' %}" class="{% if page_name == 'products' or page_name == 'mens' %}active{% endif %}dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    Hommes <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu multi-column columns-3">
                                    <div class="agile_inner_drop_nav_info">
                                        <div class="col-sm-6 multi-gd-img1 multi-gd-text ">
                                            <a href="#"><img src="{% static 'images/top2.jpg' %}" alt=" "/></a>
                                        </div>
                                        <div class="col-sm-3 multi-gd-img">
                                            <ul class="multi-column-dropdown">
                                                <li><a href="{% url 'web:mens' %}">Vêtements</a></li>
                                                <li><a href="mens.html">Portefeuilles</a></li>
                                                <li><a href="mens.html">Chaussures</a></li>
                                                <li><a href="mens.html">Montres</a></li>
                                                <li><a href="mens.html">Accessoires</a></li>
                                                <li><a href="mens.html">Sacs</a></li>
                                                <li><a href="mens.html">Casquettes et chapeaux</a></li>
                                            </ul>
                                        </div>
                                        <div class="col-sm-3 multi-gd-img">
                                            <ul class="multi-column-dropdown">
                                                <li><a href="mens.html">Bijoux</a></li>
                                                <li><a href="mens.html">Lunettes</a></li>
                                                <li><a href="mens.html">Parfums</a></li>
                                                <li><a href="mens.html">Beauté</a></li>
                                                <li><a href="mens.html">Chemises</a></li>
                                                <li><a href="mens.html">Lunettes</a></li>
                                                <li><a href="mens.html">Maillots de bain</a></li>
                                            </ul>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                </ul>
                            </li>

                            <li class="dropdown menu__item">
                                <a href="#" class="{% if page_name == 'femmes' %}active menu__item--current {% endif %}dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    Femmes <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu multi-column columns-3">
                                    <div class="agile_inner_drop_nav_info">
                                        <div class="col-sm-3 multi-gd-img">
                                            <ul class="multi-column-dropdown">
                                                <li><a href="{% url 'web:womens' %}">Vêtements</a></li>
                                                <li><a href="womens.html">Portefeuilles</a></li>
                                                <li><a href="womens.html">Chaussures</a></li>
                                                <li><a href="womens.html">Montres</a></li>
                                                <li><a href="womens.html">Accessoires</a></li>
                                                <li><a href="womens.html">Sacs</a></li>
                                                <li><a href="womens.html">Casquettes et chapeaux</a></li>
                                            </ul>
                                        </div>
                                        <div class="col-sm-3 multi-gd-img">
                                            <ul class="multi-column-dropdown">
                                                <li><a href="womens.html">Bijoux</a></li>
                                                <li><a href="womens.html">Lunettes</a></li>
                                                <li><a href="womens.html">Parfums</a></li>
                                                <li><a href="womens.html">Beauté</a></li>
                                                <li><a href="womens.html">Chemises</a></li>
                                                <li><a href="womens.html">Lunettes</a></li>
                                                <li><a href="womens.html">Maillots de bain</a></li>
                                            </ul>
                                        </div>

                                        <div class="col-sm-6 multi-gd-img multi-gd-text ">
                                            <a href="#"><img src="{% static 'images/top1.jpg' %}" alt=" "/></a>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                </ul>
                            </li>
                            <li class="{% if page_name == 'contact' %}active menu__item--current {% endif %} menu__item"><a class="menu__link" href="contact.html">Contact <span class="sr-only">{% if page_name == 'contact' %}(current){% endif %}</span></a></li>
                            {% if staff.assignee %}
                                <li class="{% if page_name == 'issues' %}active menu__item--current {% endif %} menu__item"><a class="menu__link" href="{% url 'web:issues:list' %}">Issues <span class="sr-only">{% if page_name == 'issues' %}(current){% endif %}</span></a></li>
                            {% endif %}
                            {% if staff.management %}
                                <li class="{% if 'management' in page_name %}active menu__item--current {% endif %} menu__item"><a class="menu__link" href="{% url 'web:products:create' %}">Management <span class="sr-only">{% if page_name == 'issues' %}(current){% endif %}</span></a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </div>

        <div class="top_nav_right">
            <div class="wthreecartaits wthreecartaits2 cart cart box_1">
                <form action="#" method="post" class="last">
                    <input type="hidden" name="cmd" value="_cart">
                    <input type="hidden" name="display" value="1">
                    <button class="w3view-cart" type="submit" name="submit" value="">
                        <i class="fa fa-cart-arrow-down" aria-hidden="true"></i>
                    </button>
                </form>
            </div>
        </div>

        <div class="clearfix"></div>
    </div>
</div>